<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kryolite.Rocksdb\Kryolite.Rocksdb.csproj" />
    <ProjectReference Include="..\Kryolite.Wallet\Kryolite.Wallet.csproj" />
    <ProjectReference Include="..\Kryolite.Model\Kryolite.Model.csproj" />
  </ItemGroup>

</Project>
