version: '3'

services:
  daemon-builder:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    #command: hang
    command: builder
    volumes:
      - ./daemon:/markka/daemon
      - ./shared:/markka/shared
      - ./node:/markka/node
      - daemon-build:/build

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    command: daemon
    ports:
      - 6001:6000
      - 5001:5000
    volumes:
      - ./daemon/appsettings.json:/markka/daemon/appsettings.json
      - daemon-build:/build
  daemons:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    command: daemon
    volumes:
      - ./daemon/appsettings.json:/markka/daemon/appsettings.json
      - daemon-build:/build
  louhi-miner:
    build:
      context: .
      dockerfile: Dockerfile.louhi-miner
    #command: hang
    command: miner
    volumes:
      - ./louhi-miner:/markka/louhi-miner
      - ./shared:/markka/shared
  holvi-wallet:
    build:
      context: .
      dockerfile: Dockerfile.holvi-wallet
    command: wallet
    volumes:
      - ./holvi-wallet:/markka/holvi-wallet
      - ./shared:/markka/shared
      - ./node:/markka/node
    ports:
      - 5901:5900
volumes:
  daemon-build:
