version: '3'

services:
  daemon-builder:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    #command: hang
    command: builder
    volumes:
      - ./daemon:/kryolite/daemon
      - ./shared:/kryolite/shared
      - ./node:/kryolite/node
      - daemon-build:/build

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    command: daemon
    ports:
      - 6001:6000
      - 5001:5000
    volumes:
      - ./daemon/appsettings.json:/kryolite/daemon/appsettings.json
      - /kryolite/daemon/data
      - daemon-build:/build
    environment:
      - KRYOLITE_DAEMON_CLEAN=none
  daemons:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    command: daemon
    volumes:
      - ./daemon/appsettings.json:/kryolite/daemon/appsettings.json
      - /kryolite/daemon/data
      - daemon-build:/build
    environment:
      - KRYOLITE_DAEMON_CLEAN=none
  miner:
    build:
      context: .
      dockerfile: Dockerfile.miner
    #command: hang
    command: miner
    volumes:
      - ./miner:/kryolite/miner
      - ./shared:/kryolite/shared
  wallet:
    build:
      context: .
      dockerfile: Dockerfile.wallet
    command: wallet
    volumes:
      - ./wallet:/kryolite/wallet
      - ./shared:/kryolite/shared
      - ./node:/kryolite/node
    ports:
      - 5901:5900
volumes:
  daemon-build:
