ARG PLATFORM
FROM --platform=$PLATFORM ubuntu:22.04

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  curl iputils-ping nano htop dnsutils

RUN adduser kryolite

COPY kryolite-daemon /usr/local/bin/kryolite-daemon
USER kryolite
WORKDIR /kryolite
COPY daemon/appsettings.testnet-0.json appsettings.json
ENTRYPOINT [ "/usr/local/bin/kryolite-daemon" ]
