version: '3'

services:
  daemon-builder:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    #command: hang
    command: builder
    volumes:
      - ./daemon:/markka/daemon
      - ./shared:/markka/shared
      - ./node:/markka/node
      - daemon-build:/build

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    command: daemon
    ports:
      - 6000:6000
      - 5006:5006
    volumes:
      - daemon-build:/build
  daemons:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    command: daemon
    volumes:
      - daemon-build:/build

  louhi-miner:
    build:
      context: .
      dockerfile: Dockerfile.louhi-miner
    command: hang
    #command: miner
    volumes:
      - ./louhi-miner:/markka/louhi-miner
      - ./shared:/markka/shared
volumes:
  daemon-build:
