ARG GITHUB_REPOSITORY
FROM ghcr.io/${GITHUB_REPOSITORY}/builder:base

ARG VERSION
ARG INFORMATIONAL_VERSION

COPY shared shared
COPY node node

COPY wallet wallet

ARG RUNTIME
RUN wallet/build.sh

WORKDIR /kryolite
ENTRYPOINT [ "/usr/local/bin/kryolite-wallet" ]
