ARG GITHUB_REPOSITORY
FROM ghcr.io/${GITHUB_REPOSITORY}/builder:base

COPY shared shared
COPY node node

COPY daemon daemon

ARG RUNTIME
RUN dotnet publish daemon \
  -c Release \
  -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true \
  --self-contained --runtime="$RUNTIME" \
  -o /build \
  && [ "$RUNTIME" != "win-x64" ] && mv /build/daemon /usr/local/bin/kryolite-daemon || true \
  && rm -rf /build

WORKDIR /kryolite
ENTRYPOINT [ "/usr/local/bin/kryolite-daemon" ]
