ARG GITHUB_REPOSITORY
FROM ghcr.io/${GITHUB_REPOSITORY}/builder:base

COPY shared shared

COPY miner miner

ARG RUNTIME
RUN dotnet publish miner \
  -c Release \
  -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true \
  --self-contained --runtime="$RUNTIME" \
  -o /build
