version: '3'

services:
  base:
    image: "ghcr.io/${GITHUB_REPOSITORY:-kryolite-krypto}/builder:base"
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - "ghcr.io/${GITHUB_REPOSITORY:-kryolite-krypto}/builder:base"
    networks:
      - builder
  daemon:
    depends_on:
      - base
    image: "ghcr.io/${GITHUB_REPOSITORY:-kryolite-krypto}/builder:daemon-${VARIANT:-linux-x64}"
    build:
      context: .
      dockerfile: Dockerfile.builder.daemon
      args:
        BUILDKIT_INLINE_CACHE: 1
        GITHUB_REPOSITORY: ${GITHUB_REPOSITORY:-kryolite-crypto}
        RUNTIME: ${RUNTIME:-linux-x64}
      cache_from:
        - "ghcr.io/${GITHUB_REPOSITORY:-kryolite-krypto}/builder:daemon-${VARIANT:-linux-x64}"
    networks:
      - builder
    volumes:
      - ./daemon/appsettings.daemons.json:/kryolite/appsettings.json
  miner:
    depends_on:
      - base
    image: "ghcr.io/${GITHUB_REPOSITORY:-kryolite-krypto}/builder:miner-${VARIANT:-linux-x64}"
    build:
      context: .
      dockerfile: Dockerfile.builder.miner
      args:
        BUILDKIT_INLINE_CACHE: 1
        GITHUB_REPOSITORY: ${GITHUB_REPOSITORY:-kryolite-crypto}
        RUNTIME: ${RUNTIME:-linux-x64}
      cache_from:
        - "ghcr.io/${GITHUB_REPOSITORY:-kryolite-krypto}/builder:miner-${VARIANT:-linux-x64}"
    networks:
      - builder
    entrypoint:
      - /usr/bin/tail
      - -f
      - /dev/null
  kryolite:
    depends_on:
      - base
    image: "ghcr.io/${GITHUB_REPOSITORY:-kryolite-krypto}/builder:kryolite-${VARIANT:-linux-x64}"
    build:
      context: .
      dockerfile: Dockerfile.builder.kryolite
      args:
        BUILDKIT_INLINE_CACHE: 1
        GITHUB_REPOSITORY: ${GITHUB_REPOSITORY:-kryolite-crypto}
        RUNTIME: ${RUNTIME:-linux-x64}
      cache_from:
        - "ghcr.io/${GITHUB_REPOSITORY:-kryolite-krypto}/builder:kryolite-${VARIANT:-linux-x64}"
    networks:
      - builder
    entrypoint:
      - /usr/bin/tail
      - -f
      - /dev/null
  wallet:
    depends_on:
      - base
    image: "ghcr.io/${GITHUB_REPOSITORY:-kryolite-krypto}/builder:wallet-${VARIANT:-linux-x64}"
    build:
      context: .
      dockerfile: Dockerfile.builder.wallet
      args:
        BUILDKIT_INLINE_CACHE: 1
        GITHUB_REPOSITORY: ${GITHUB_REPOSITORY:-kryolite-crypto}
        RUNTIME: ${RUNTIME:-linux-x64}
      cache_from:
        - "ghcr.io/${GITHUB_REPOSITORY:-kryolite-krypto}/builder:wallet-${VARIANT:-linux-x64}"
    networks:
      - builder
    entrypoint:
      - /usr/bin/tail
      - -f
      - /dev/null

networks:
  builder:
