version: '3'

services:
  daemon:
    build:
      context: .
      dockerfile: Dockerfile.release.daemon
      x-bake:
        tags:
          - ghcr.io/${GITHUB_REPOSITORY:-kryolite-crypto/kryolite}/daemon:latest
        platforms:
          - linux/amd64
          - linux/arm64
  miner:
    build:
      context: .
      dockerfile: Dockerfile.release.miner
      x-bake:
        tags:
          - ghcr.io/${GITHUB_REPOSITORY:-kryolite-crypto/kryolite}/miner:latest
        platforms:
          - linux/amd64
          - linux/arm64
