version: '3'

services:
  daemon-manual:
    build:
      context: .
      dockerfile: Dockerfile.daemon-manual
  daemon-script:
    build:
      context: .
      dockerfile: Dockerfile.daemon-script
