ARG GITHUB_REPOSITORY
FROM ghcr.io/${GITHUB_REPOSITORY}/builder:base

COPY shared shared
COPY node node

COPY cli cli

ARG RUNTIME
RUN dotnet publish cli \
  -c Release \
  -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true \
  --self-contained --runtime="$RUNTIME" \
  -o /build \
  && [ "$RUNTIME" != "win-x64" ] && mv /build/cli /usr/local/bin/kryolite || true \
  && rm -rf /build

WORKDIR /kryolite
ENTRYPOINT [ "/usr/local/bin/kryolite" ]
