FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
  nano htop iputils-ping curl dnsutils \
  && useradd --home /kryolite --no-create-home kryolite

COPY --from=builder /usr/local/bin/kryolite-miner /usr/local/bin
WORKDIR /kryolite
COPY daemon/appsettings.testnet-0.json appsettings.json

ENTRYPOINT [ "/usr/local/bin/kryolite-daemon" ]
