<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>kryolite-miner</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Optimize>true</Optimize>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <PublishAot>true</PublishAot>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <SelfContained>true</SelfContained>
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
    <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Kryolite.Module.Mdns/Kryolite.Module.Mdns.csproj" />
    <ProjectReference Include="../Kryolite.Shared/Kryolite.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Microsoft.DotNet.ILCompiler" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\licenses.txt" CopyToPublishDirectory="Always" />
  </ItemGroup>
</Project>
