<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kryolite.Shared\Kryolite.Shared.csproj" />
    <ProjectReference Include="..\Kryolite.Transport.Websocket\Kryolite.Transport.Websocket.csproj" />
  </ItemGroup>
</Project>
