<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Wasmtime" Version="19.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kryolite.Type\Kryolite.Type.csproj" />
    <ProjectReference Include="..\Kryolite.Interface\Kryolite.Interface.csproj" />
    <ProjectReference Include="..\Kryolite.Model\Kryolite.Model.csproj" />
  </ItemGroup>
</Project>
