name: build

on:
  push:

jobs:
  # builder:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: docker build -f Dockerfile.builder -t builder .
  build:
    #    needs: builder
    strategy:
      matrix:
        component: [daemon, holvi-wallet, louhi-miner]
        runtime: [linux-x64, linux-arm64, mac-x64, mac-arm64, win-x64]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: docker build -f Dockerfile.builder -t builder .
      - run: mkdir dist
      - run: docker run -v "$(pwd)/dist:/dist" builder "${{ matrix.component }}" "${{ matrix.runtime }}" /dist
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.component }}-${{ matrix.runtime }}
          path: dist
  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -lah
