on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - run: ./build.sh linux-x64
      - run: ./test.sh
