on:
  release:
    types:
      - prereleased

jobs:
  builds:
    strategy:
      matrix:
        component: [daemon, wallet, miner]
        variant: [linux-x64, linux-arm64, mac-x64, mac-arm64, win-x64]
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - run: mkdir dist
      - run: ./build.sh "${{ matrix.component }}" "${{ matrix.variant }}" dist
      - run: docker push "ghcr.io/${GITHUB_REPOSITORY}/builder:base"
      - run: docker push "ghcr.io/${GITHUB_REPOSITORY}/builder:${{ matrix.component }}-${{ matrix.runtime }}"
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*
