on:
  release:
    types:
      - prereleased

jobs:
  base:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - run: ./build.sh linux-x64 base
      - run: docker-compose -f docker-compose.builder.yml push base

  builds:
    needs: base
    strategy:
      matrix:
        component: [daemon, wallet, miner, kryolite]
        #variant: [linux-x64, linux-arm64, mac-x64, mac-arm64, win-x64]
        variant: [linux-x64, linux-arm64]
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - run: ./build.sh "${{ matrix.variant }}" "${{ matrix.component }}"
      - run: docker push "ghcr.io/${GITHUB_REPOSITORY}/builder:${{ matrix.component }}-${{ matrix.variant }}"
      - run: mkdir dist
      - run: ./package.sh "${{ matrix.variant }}" dist "${{ matrix.component }}"
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*

  docker:
    needs: builds
    strategy:
      matrix:
        component: [daemon, miner]
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - run: docker buildx create --use
      - run: ./docker.sh "${{ matrix.component }}" latest "$GITHUB_SHA" "$GITHUB_REF_NAME"
